# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#Animal.create(animal_name: "Pig", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTkkbcmQ3SlibVstRHrYEKGhk2-Fx9kt8-xYT5Gz7F8YU849xHryg")
#Animal.create(animal_name: "Horse", url: "http://www.horsechannel.com/images/horse-news-article-images/chestnut-horse-autumn_1000.jpg")
Animal.create(animal_name: "Alligator", url: "http://cdn.images.express.co.uk/img/dynamic/78/590x/secondary/alligators-571014.jpg")
Animal.create(animal_name: "Ant", url: "http://dreamicus.com/data/ant/ant-05.jpg")
Animal.create(animal_name: "Bear", url: "http://static.boredpanda.com/blog/wp-content/uploads/2016/09/mother-bear-cubs-animal-parenting-21-57e3a2161d7f7__880.jpg")
Animal.create(animal_name: "Bee", url: "http://yourshot.nationalgeographic.com/u/ss/fQYSUbVfts-T7pS2VP2wnKyN8wxywmXtY0-FwsgxpCrcJO9rnvc0MhB8vLF3_Hflr-DyKKgGeVcUxqDT1sVz/")
Animal.create(animal_name: "Bird", url: "http://www.nature.org/cs/groups/webcontent/@web/@pennsylvania/documents/media/indigo-bunting-720x400.jpg")
Animal.create(animal_name: "Butterfly", url: "https://s-media-cache-ak0.pinimg.com/736x/08/7d/7f/087d7f0069385dd543178c4c2fca3430.jpg")
Animal.create(animal_name: "Cat", url: "http://www.popsci.com/sites/popsci.com/files/styles/large_1x_/public/images/2016/08/1200px-chat_des_sables_felis_margarita.jpeg?itok=ISrKp-wL&fc=50,50")
Animal.create(animal_name: "Cheetah", url: "https://static1.squarespace.com/static/54f738bee4b08d5963bb05bf/t/54ff4f98e4b033cba9481ec6/1426018202405/ec6dae614acb.jpg?format=1500w")
Animal.create(animal_name: "Chicken", url: "http://www.gourmetsleuth.com/images/default-source/articles/big-white-chicken.jpg?sfvrsn=8")
Animal.create(animal_name: "Cow", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Cow_female_black_white.jpg/1200px-Cow_female_black_white.jpg")
Animal.create(animal_name: "Crocodile", url: "http://www.outback-australia-travel-secrets.com/image-files/crocodile-attacks-4.jpg")
Animal.create(animal_name: "Deer", url: "http://www.hudson.oh.us/ImageRepository/Document?documentID=2585")
Animal.create(animal_name: "Camel", url: "http://farm3.static.flickr.com/2619/4106977090_c56c14cab1.jpg")
Animal.create(animal_name: "Dog", url: "https://cdn.pixabay.com/photo/2016/02/19/15/46/dog-1210559_960_720.jpg")
Animal.create(animal_name: "Dolphin", url: "https://s-media-cache-ak0.pinimg.com/originals/a2/36/b5/a236b548637a9758bf8eb8fe666cc33a.jpg")
Animal.create(animal_name: "Duck", url: "http://media-cdn.tripadvisor.com/media/photo-s/03/75/bf/56/wild-duck.jpg")
Animal.create(animal_name: "Eagle", url: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Bald_Eagle_Head_2_(6021915997).jpg")
Animal.create(animal_name: "Elephant", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7wkab4YNBu9jEBBMy47pZfp2DTfrFGgntUHgtgbrefaupQtMNbw")
Animal.create(animal_name: "Fish", url: "https://s-media-cache-ak0.pinimg.com/736x/0b/25/34/0b2534091d482a4a2269bd65a972d7c5.jpg")
Animal.create(animal_name: "Fly", url: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Pollenia-sp-Cluster-fly-20100718a.jpg")
Animal.create(animal_name: "Fox", url: "https://s-media-cache-ak0.pinimg.com/originals/26/05/75/260575bf1fc0c380d2d2c3288564b30c.jpg")
Animal.create(animal_name: "Frog", url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSAgEMB0vHs_EgTVR82XSMR99GFxG4ShIxSabGzFEQfq7hJXoKn")
Animal.create(animal_name: "Giraffe", url: "https://giraffeconservation.org/wp-content/uploads/2016/02/gcf-15-of-37.jpg")
Animal.create(animal_name: "Goat", url: "http://cdn.images.express.co.uk/img/dynamic/78/590x/secondary/goat-523061.jpg")
Animal.create(animal_name: "Goldfish", url: "http://sunlandwatergardens.com/wp-content/uploads/2013/06/Pond_fishGoldfishRed-FantailFantail-goldfishgoldfish-for-ponds.jpg")
Animal.create(animal_name: "Hamster", url: "http://www.sciencemag.org/sites/default/files/styles/article_main_large/public/images/sn-hamster.jpg?itok=YkpKAYNJ")
Animal.create(animal_name: "Hippopotamus", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPZbcjCh8JkvFjEI5UbmcfoQzWCrHJMhC1W3UfxCd1jJCZqacqeg")
Animal.create(animal_name: "Kangaroo", url: "https://i.guim.co.uk/img/media/96179c5762e526e05ad68d35e1e4eb9b961b0422/640_1244_4112_2466/4112.jpg?w=460&q=55&auto=format&usm=12&fit=max&s=092fcdd2d342ebd3f7502666c72cbbe0")
Animal.create(animal_name: "Kitten", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRYgLXuYrWDOjljZn8gAhpeVECuBUeFPAvSnHaV-sGke0dBVQxDjQ")
Animal.create(animal_name: "Llama", url: "https://s-media-cache-ak0.pinimg.com/564x/b9/b1/45/b9b1453e7c64ee9ca2f3f8911f4401e9.jpg")
Animal.create(animal_name: "Lion", url: "http://kids.nationalgeographic.com/content/dam/kids/photos/animals/Mammals/H-P/lion-male-roar.jpg.adapt.945.1.jpg")
Animal.create(animal_name: "Lobster", url: "http://pngimg.com/uploads/lobster/lobster_PNG14262.png")
Animal.create(animal_name: "Monkey", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSP9wyqCXkACSjAIOaWQvmTd7k1hP5247JDkzGXZ-fLiAz2Sca0Gw")
Animal.create(animal_name: "Octopus", url: "http://pixel.nymag.com/imgs/daily/science/2016/12/19/19-octopus.w710.h473.2x.jpg")
Animal.create(animal_name: "Owl", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_(1).jpg/170px-Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_(1).jpg")
Animal.create(animal_name: "Panda", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhWKr2lSzPMQ6RCQ7Uvkk5DZu92ARP7mowxaHcMM1LABbK-rxC")
Animal.create(animal_name: "Puppy", url: "http://animalfair.com/wp-content/uploads/2013/09/macexplorer.com-puppy-dog-26.jpg")
Animal.create(animal_name: "Rabbit", url: "https://s-media-cache-ak0.pinimg.com/originals/df/1b/9f/df1b9fc4e0c6bd38cc5c716de4b9e8cb.jpg")
Animal.create(animal_name: "Rat", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSeH2ztRiv2GKSdi32Uh8WM89_i8jy1tjeAeUa01GxvOS2Ol8PI")
Animal.create(animal_name: "Scorpion", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQA5ZooKyxskX6LLPmNdnQzjHWp4OsL553jf-JEt4ow7Fm2oyVI")
Animal.create(animal_name: "Seal", url: "http://insider.si.edu/wordpress/wp-content/uploads/2014/05/CARIBBEAN-MONK-SEALRET2-630x410.jpg")
Animal.create(animal_name: "Shark", url: "http://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2015/08/18/102930512-Great_white_shark.1910x1000.jpg")
Animal.create(animal_name: "Sheep", url: "http://www.ravishly.com/sites/default/files/ThinkstockPhotos-182344013.jpg")
Animal.create(animal_name: "Snail", url: "http://images2.onionstatic.com/clickhole/2184/4/16x9/800.jpg")
Animal.create(animal_name: "Snake", url: "http://www.ecologyasia.com/images-pqr/paradise-tree-snake_3022.jpg")
Animal.create(animal_name: "Spider", url: "http://www.livescience.com/images/i/000/079/136/original/bradford-green-magnolia.jpg?interpolation=lanczos-none&downsize=*:1000")
Animal.create(animal_name: "Squirrel", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMkG3IA1-9fNn228VAbK164M3t8lxBry2Dz1UtqnDuw17nizAK")
Animal.create(animal_name: "Swan", url: "http://www.coolkidfacts.com/wp-content/uploads/2015/03/elegant-swans.jpg")
Animal.create(animal_name: "Tiger", url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ5iS3guFbUM6UDtaZ0w9XEG8UCCSMUweS8qNYl46zQfvG1R4zc7w")
Animal.create(animal_name: "Turtle", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyqR2BQTS1_z96YvQq4tfi5q4rMu76WMM2rp10mI2QyCbQJoGZ")
Animal.create(animal_name: "Unicorn", url: "http://i.huffpost.com/gen/2424200/images/o-UNICORN-facebook.jpg")
Animal.create(animal_name: "Whale", url: "http://cdn.natgeotv.com.au/factsheets/thumbnails/UnderstandingTheBlueWhale_whale.jpg?v=18&azure=false&scale=both&width=1600&height=900&mode=crop")
Animal.create(animal_name: "Wolf", url: "https://i.cbc.ca/1.3476516.1457118314!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_940/wolf-howling.jpg")
Animal.create(animal_name: "Zebra", url: "https://gifts.worldwildlife.org/gift-center/Images/large-species-photo/large-Zebra-photo.jpg")







